import type { Metadata } from "next";
import { Onest } from "next/font/google"
import { Header } from "@/components/header/header"
import "./globals.css"
import { ActiveSectionProvider } from "@/context/active-section/active-section-context";

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${onest.className} antialiased pt-8 bg-gray-03`}>
                <ActiveSectionProvider>
                    <Header />
                    <main>
                        {children}
                    </main>
                </ActiveSectionProvider>
            </body>
        </html>
    );
}
