import type { Metadata } from "next";
import { Onest } from "next/font/google"
import { Header } from "@/components/header/header"
import "./globals.css"
import { ActiveSectionProvider } from "@/context/active-section/active-section-context";
import Image from "next/image";

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${onest.className} antialiased pt-8 bg-gray-03`}>
                <ActiveSectionProvider>
                    <Header />
                    <Image
                        src='/background.png'
                        alt="background"
                        fill
                        className="z-0"
                    />
                    <main className="relative z-40">
                        {children}
                    </main>
                </ActiveSectionProvider>
            </body>
        </html>
    );
}
